# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.TextField()),
                ('blog_content', models.TextField()),
                ('blog_pubdate', models.DateTimeField(verbose_name='published date')),
                ('blog_author', models.CharField(max_length=100)),
            ],
        ),
    ]
