# Generated by Django 2.0 on 2018-01-03 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Optionsdtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_txt', models.TextField()),
                ('option_createdt', models.DateTimeField(default=datetime.datetime(2018, 1, 4, 0, 8, 56, 346807), verbose_name='created date')),
                ('option_moddt', models.DateTimeField(default=datetime.datetime(2018, 1, 4, 0, 8, 56, 346807), verbose_name='modified date')),
                ('option_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questiondtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_title', models.CharField(max_length=1000)),
                ('ques_content', models.TextField(blank=True, default='')),
                ('ques_author', models.CharField(default='', max_length=200)),
                ('ques_createdt', models.DateTimeField(default=datetime.datetime(2018, 1, 4, 0, 8, 56, 346807), verbose_name='created date')),
                ('ques_moddt', models.DateTimeField(default=datetime.datetime(2018, 1, 4, 0, 8, 56, 346807), verbose_name='modified date')),
                ('ques_sponsored', models.CharField(default='N', max_length=1)),
                ('ques_category', models.CharField(default='', max_length=200)),
                ('ques_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='optionsdtl',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.Questiondtl'),
        ),
    ]
