# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='createdt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 18, 42, 56, 492107)),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fblogin',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gpluslogin',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='modifieddt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 18, 42, 56, 492262)),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userimg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
