# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20171227_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Mname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Sex',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lastlogindt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 18, 47, 19, 113666)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Emailid',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='createdt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 18, 47, 19, 113403)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='modifieddt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 18, 47, 19, 113555)),
        ),
    ]
