# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20171227_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Mname',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Password',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='createdt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 18, 51, 13, 843622)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fblogin',
            field=models.CharField(default='N', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gpluslogin',
            field=models.CharField(default='N', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lastlogindt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 18, 51, 13, 843877)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='modifieddt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 27, 18, 51, 13, 843756)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userimg',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
