# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20171227_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Lname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Mname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Sex',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='createdt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 13, 50, 24, 55669)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fblogin',
            field=models.CharField(blank=True, default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gpluslogin',
            field=models.CharField(blank=True, default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lastlogindt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 13, 50, 24, 55954)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='modifieddt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 13, 50, 24, 55824)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userimg',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
