# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20171228_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='createdt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 13, 52, 22, 530704)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lastlogindt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 13, 52, 22, 530967)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='modifieddt',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 13, 52, 22, 530845)),
        ),
    ]
