# Generated by Django 2.0 on 2018-01-01 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20180101_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='createdt',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 21, 20, 34, 771565)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lastlogindt',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 21, 20, 34, 771565)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='modifieddt',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 21, 20, 34, 771565)),
        ),
    ]
